name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "paalamugan44@gmail.com"
        git config --global user.name "paalamugan"

    - name: Setup npmrc
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

    - name: setup pnpm config
      shell: bash
      run: pnpm config set store-dir $PNPM_CACHE_FOLDER

    - name: Install dependencies
      shell: bash
      run: pnpm install
